---
services: docker

env:
  - distro: centos7

script:
  - sudo pip install "ansible-run>=2.1"
  - echo "        jdk_url: $JDK_URL" >> test/test.yml
  - echo "        jvm_zipfile: $JVM_ZIPFILE" >> test/test.yml
  - image=$distro ansible-test test/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/